// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYqPh5_JrVSwuGbj2-wFsvln6IM-QLNNM',
    appId: '1:923045864782:web:6f7d33eb026390d5ab2a1f',
    messagingSenderId: '923045864782',
    projectId: 'smartapp-elf',
    authDomain: 'smartapp-elf.firebaseapp.com',
    storageBucket: 'smartapp-elf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGEC6AmAGKQvMU70wlktS5PZTqT9KbMEk',
    appId: '1:923045864782:android:96a96bf7ff672801ab2a1f',
    messagingSenderId: '923045864782',
    projectId: 'smartapp-elf',
    storageBucket: 'smartapp-elf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiOdYvorfj5lbJw1ZX3lHFBCYq_kI-pkg',
    appId: '1:923045864782:ios:1197f9110641ac80ab2a1f',
    messagingSenderId: '923045864782',
    projectId: 'smartapp-elf',
    storageBucket: 'smartapp-elf.firebasestorage.app',
    iosBundleId: 'elfaize.smartAppElfaize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiOdYvorfj5lbJw1ZX3lHFBCYq_kI-pkg',
    appId: '1:923045864782:ios:1197f9110641ac80ab2a1f',
    messagingSenderId: '923045864782',
    projectId: 'smartapp-elf',
    storageBucket: 'smartapp-elf.firebasestorage.app',
    iosBundleId: 'elfaize.smartAppElfaize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYqPh5_JrVSwuGbj2-wFsvln6IM-QLNNM',
    appId: '1:923045864782:web:4579cb13e5059a47ab2a1f',
    messagingSenderId: '923045864782',
    projectId: 'smartapp-elf',
    authDomain: 'smartapp-elf.firebaseapp.com',
    storageBucket: 'smartapp-elf.firebasestorage.app',
  );
}
